
-- ==========================================
-- SHELLY SPANISH ISLAND - SAFE SETUP SCRIPT
-- ==========================================
-- Run this in the Supabase SQL Editor.
-- It is safe to run multiple times (Idempotent).

-- 0. CLEANUP LEFTOVERS (Fix Dashboard Warnings)
-- This removes the "Security Definer" warning you saw.
-- Our app calculates stats on the client-side, so this legacy view is not needed.
drop view if exists public.user_progress_stats;

-- 1. Create Profiles Table (Safe Check)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamptz default now()
);

-- 2. Add Columns Safely (Only adds if missing)
do $$
begin
  -- Basic Profile Info
  if not exists (select 1 from information_schema.columns where table_name='profiles' and column_name='traveler_name') then
    alter table public.profiles add column traveler_name text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='profiles' and column_name='avatar_id') then
    alter table public.profiles add column avatar_id text default 'default';
  end if;
  
  -- Premium/Subscription Fields
  if not exists (select 1 from information_schema.columns where table_name='profiles' and column_name='is_premium') then
    alter table public.profiles add column is_premium boolean default false;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='profiles' and column_name='premium_until') then
    alter table public.profiles add column premium_until timestamptz;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='profiles' and column_name='subscription_id') then
    alter table public.profiles add column subscription_id text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='profiles' and column_name='customer_id') then
    alter table public.profiles add column customer_id text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='profiles' and column_name='variant_name') then
    alter table public.profiles add column variant_name text;
  end if;
end $$;

-- 3. Enable Security (RLS) for Profiles
alter table public.profiles enable row level security;

-- 4. Re-apply Profile Policies (Drop first to avoid conflicts)
drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile" on public.profiles for select using ( auth.uid() = id );

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile" on public.profiles for update using ( auth.uid() = id );

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile" on public.profiles for insert with check ( auth.uid() = id );

-- 5. Create Progress Table (Safe Check)
create table if not exists public.user_word_choices (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  word_id text not null,
  level int default 0,
  next_review_date text,
  ease_factor float default 2.5,
  failure_count int default 0,
  updated_at timestamptz default now(),
  unique(user_id, word_id)
);

-- 6. Enable Security (RLS) for Progress
alter table public.user_word_choices enable row level security;

-- 7. Re-apply Progress Policies
drop policy if exists "Users can manage own progress" on public.user_word_choices;
create policy "Users can manage own progress" on public.user_word_choices for all using ( auth.uid() = user_id );

-- 8. Auto-update timestamp triggers (Safe)
create extension if not exists moddatetime;

drop trigger if exists handle_updated_at on public.profiles;
create trigger handle_updated_at before update on public.profiles
  for each row execute procedure moddatetime (updated_at);

drop trigger if exists handle_updated_at on public.user_word_choices;
create trigger handle_updated_at before update on public.user_word_choices
  for each row execute procedure moddatetime (updated_at);
